name: Setup
description: Setup the environment

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: .node-version
        cache: pnpm
        registry-url: https://registry.npmjs.org

    - name: Upgrade npm for trusted publishing
      shell: bash
      run: npm install -g npm@latest

    - name: Install Dependencies
      shell: bash
      run: pnpm i
