name: Setup
description: Setup the environment

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: .node-version
        cache: pnpm
        registry-url: https://registry.npmjs.org

    - name: Upgrade npm for trusted publishing
      shell: bash
      run: npm install -g npm@latest

    - name: Install Dependencies
      shell: bash
      run: pnpm i
