name: Setup
description: Setup the environment

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

    - name: Setup Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm i
