name: Setup
description: Setup the environment

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: Setup Node.js
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm i
