dedupePeers: true
publicHoistPattern:
  - "@types/emscripten"
allowBuilds:
  esbuild: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - "@vitest/browser-playwright@4.1.10"
  - "@vitest/browser@4.1.10"
  - "@vitest/coverage-istanbul@4.1.10"
  - "@vitest/expect@4.1.10"
  - "@vitest/mocker@4.1.10"
  - "@vitest/pretty-format@4.1.10"
  - "@vitest/runner@4.1.10"
  - "@vitest/snapshot@4.1.10"
  - "@vitest/spy@4.1.10"
  - "@vitest/ui@4.1.10"
  - "@vitest/utils@4.1.10"
  - concurrently@10.0.5
  - type-fest@5.8.0
  - vite@8.2.1
  - vitest@4.1.10
  - zxing-wasm@3.1.3
