dedupePeers: true
publicHoistPattern:
  - "@types/emscripten"
allowBuilds:
  esbuild: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - "@vitest/browser-playwright@4.1.8"
  - "@vitest/browser@4.1.8"
  - "@vitest/coverage-istanbul@4.1.8"
  - "@vitest/expect@4.1.8"
  - "@vitest/mocker@4.1.8"
  - "@vitest/pretty-format@4.1.8"
  - "@vitest/runner@4.1.8"
  - "@vitest/snapshot@4.1.8"
  - "@vitest/spy@4.1.8"
  - "@vitest/ui@4.1.8"
  - "@vitest/utils@4.1.8"
  - concurrently@10.0.1
  - type-fest@5.7.0
  - vite@8.0.16
  - vitest@4.1.8
  - zxing-wasm@3.1.0
